services:
  bankiru_api.test.uuid_generator:
    public: false
    class: ScayTrase\Api\IdGenerator\UuidGenerator

  bankiru_api.test.test_guzzle_mock:
    class: GuzzleHttp\Handler\MockHandler

  bankiru_api.test.test_rpc_client:
    class: Bankiru\Api\Test\TestClient
    public: false
    arguments:
    - "@bankiru_api.test.test_guzzle_mock"
    - "@bankiru_api.test.uuid_generator"
    tags:
    - { name: rpc_client, client_name: test_client }

  test_rpc_client:
    alias: bankiru_api.test.test_rpc_client

  debug.stopwatch:
    class: Symfony\Component\Stopwatch\Stopwatch
